services:
  - type: web
    name: ecommerce-svc
    runtime: node
    branch: develop
    buildCommand: npm install && npm run build
    startCommand: node ./dist/index.js  # Assuming index.js is your entry point for JavaScript
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: '*'
    plan: free